services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
     - my-net

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
     - 5432:80
   environment:
     - PMA_HOST=mysql
   networks:
     - my-net

networks:
    my-net: { }
